# Snakefile

configfile: "config/config.yaml"

# --- STEP 1: Structure Preparation ---
rule prepare_structure:
    input:
        pdb = "data/inputs/target.pdb"
    output:
        output_pdbqt = "data/interim/target.pdbqt"
    shell:
        "obabel -ipdb {input.pdb} -opdbqt -O {output.output_pdbqt} -xr -h --partialcharge gasteiger 2> /dev/null"


# 3. The rule that runs your Python script
rule run_docking:
    input:
        receptor = "data/raw/receptor.pdbqt",
        ligand = "data/raw/ligand.pdbqt"
    output:
        docked = "data/results/output.pdbqt"
    params:
        # Pull values from the loaded config file
        
    # Option A: Run your script directly inside the current environment
    script:
        "workflow/scripts/docking_script_natural_bs.sh"